[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Mixed_Poisson"
version = "0.1"
dependencies = ["numpy", "firedrake", "matplotlib"]

[tool.hatch.build.targets.wheel]
packages = ["Mixed_Poisson"]